# Generated by Django 5.0.3 on 2024-04-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img_url',
            field=models.URLField(default=''),
        ),
    ]
