# Generated by Django 5.0.3 on 2024-04-18 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('seller', '0002_food_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.food'),
        ),
    ]
